### ISSUE TITLE
save as draft

### ISSUE THREAD

**Issue by CooperFLe** [mugdha-gupta/3354-UTDisaster#12]
I already have boiler plate in place for executing code when text fields are updated by the user in [NewMessageActivity.java](https://github.com/mugdha-gupta/3354-UTDisaster/blob/master/UTDMer/app/src/main/java/com/utdisaster/utdmer/NewMessageActivity.java#L27-L49)

We'll need to keep local data that ties the message in `messageField` to the number in `recipientField`. This could be accomplished by using `onTextChanged` in the `messageField`. Whenever this method is invoked, save the contents of `messageField` in a data structure attached to the contents of `recipientField`. One option for this would be a `HashMap` using `recipientField` as the key and `messageField` as the value.

Then in order to restore drafts, you will need to utilise the `beforeTextChanged` and `onTextChanged` of the `recipientField`. You'll want to save the contents of `recipientField` to the `HashMap` discussed above when the value of `s` in `beforeTextChanged` is a valid phone number. Then you'll want to retrieve the value saved in `HashMap` and display it in `messageField` when the value of `s` in `onTextChanged` is a valid phone number.

Some documentation that you may find useful.

https://developer.android.com/reference/android/text/TextWatcher
https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html
https://developer.android.com/guide/topics/data/data-storage

**Comment by mugdha-gupta** [comment]
getDraft should run when you click on the draft message, right?

**Comment by CooperFLe** [comment]
@xwnn it would be a better UX for the drafts functionality to function automatically with the TextWatcher. If you can't get that implemented, you'll also need a way to delete drafts.
