### ISSUE TITLE
implement conversations

### ISSUE THREAD

**Issue by CooperFLe** [mugdha-gupta/3354-UTDisaster#16]
Instead of displaying all of the messages in the main activity, it would be nice to see a list of conversations instead where you can see messages you have either sent or received in the conversation itself.

Open to suggestions on how to accomplish this, but we will need to focus on closing the requirement issues first.

**Comment by mugdha-gupta** [comment]
@CooperFLe I am creating a Conversation class and a ConversationUtility, and therefore am thinking about adding a conversationId to the Sms class. I don't understand how parseSmsCursor works and if the conversationId can be set in this method.

**Comment by CooperFLe** [comment]
@mugdha-gupta do not mess with parseSmsCursor or anything else that is working with the content uri. It is an undocumented workflow and very touchy. Conversations will just be based on the address since we are not implementing group messaging. You can just implement your Conversation class joining messages based on their `address` field.
